"$schema" = 'https://starship.rs/config-schema.json'

format = """
$git_branch\
$git_status\
$directory\
$python$rust$nodejs$lua$golang$java$kotlin$swift\
$cmd_duration\
$time\
$line_break\
$character"""



[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%H:%M"
style = "fg:#6272a4"

[cmd_duration]
min_time = 500
format = '[\($duration\)]($style) '
style = "fg:#f1fa8c"

[git_branch]
symbol = " "
format = '[$symbol$branch]($style) '
style = "fg:#bd93f9"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "fg:#ff79c6"

[directory]
read_only = " 󰌾"
style = "fg:#8be9fd"

[character]
success_symbol = "[❯](fg:#50fa7b)"
error_symbol = "[❯](fg:#ff5555)"

[aws]
symbol = " "
[azure]
symbol = " "
[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
[buf]
symbol = " "
[bun]
symbol = " "
[c]
symbol = " "
[cpp]
symbol = " "
[cmake]
symbol = " "
[cobol]
symbol = " "
[conda]
symbol = " "
[container]
symbol = " "
[crystal]
symbol = " "
[dart]
symbol = " "
[deno]
symbol = " "
[direnv]
symbol = " "
[docker_context]
symbol = " "
[dotnet]
symbol = " "
[elixir]
symbol = " "
[elm]
symbol = " "
[erlang]
symbol = " "
[fennel]
symbol = " "
[fortran]
symbol = " "
[fossil_branch]
symbol = " "
[gcloud]
symbol = "󱇶 "
[gleam]
symbol = " "
[git_commit]
tag_symbol = '  '
[golang]
symbol = " "
[gradle]
symbol = " "
[guix_shell]
symbol = " "
[haskell]
symbol = " "
[haxe]
symbol = " "
[helm]
symbol = " "
[hg_branch]
symbol = " "
[hostname]
ssh_symbol = " "
[java]
symbol = " "
[julia]
symbol = " "
[kotlin]
symbol = " "
[kubernetes]
symbol = "󱃾 "
[lua]
symbol = " "
[maven]
symbol = " "
[memory_usage]
symbol = "󰍛 "
[meson]
symbol = "󰔷 "
[mojo]
symbol = "󰈸 "
[nats]
symbol = " "
[netns]
symbol = "󰛳 "
[nim]
symbol = " "
[nix_shell]
symbol = " "
[nodejs]
symbol = " "
[ocaml]
symbol = " "
[odin]
symbol = "󰟢 "
[opa]
symbol = " "
[openstack]
symbol = " "
[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "
[package]
symbol = "󰏗 "
[perl]
symbol = " "
[php]
symbol = " "
[pijul_channel]
symbol = " "
[pixi]
symbol = "󰏗 "
[pulumi]
symbol = " "
[purescript]
symbol = " "
[python]
symbol = " "
[raku]
symbol = "󱖊 "
[red]
symbol = "󱍼 "
[rlang]
symbol = "󰟔 "
[ruby]
symbol = " "
[rust]
symbol = "󱘗 "
[scala]
symbol = " "
[shlvl]
symbol = "󰹍 "
[singularity]
symbol = " "
[solidity]
symbol = " "
[spack]
symbol = " "
[status]
symbol = " "
[sudo]
symbol = " "
[swift]
symbol = " "
[terraform]
symbol = " "
[vlang]
symbol = " "
[typst]
symbol = " "
[vagrant]
symbol = " "
[xmake]
symbol = " "
[zig]
symbol = " "
